---
- name: Kubernetes Data Collection | Write kubernetes heapster yaml
  template:
      src:  heapster.yml.j2
      dest: "{{kube_config_dir}}/heapster.yml"
      mode: 0644

- name: Kubernetes Data Collection | Check if heapster svc exists
  command: "{{ bin_dir }}/kubectl get svc heapster -n {{system_namespace}}"
  register: 'heapstersvc'
  changed_when: False
  failed_when: False
  
- name: Kubernetes Data Collection | Check if heapster deploy exists
  command: "{{ bin_dir }}/kubectl get deploy heapster -n {{system_namespace}}"
  register: 'heapsterdeploy'
  changed_when: False
  failed_when: False

- name: Kubernetes Data Collection | Start kubernetes heapster app
  kube:
      name: "heapster"
      kubectl: "{{bin_dir}}/kubectl"
      filename: "{{kube_config_dir}}/heapster.yml"
      namespace: "{{system_namespace}}"
  when: heapstersvc|failed and heapsterdeploy|failed
#  ignore_errors: yes
