---
- hosts: kube-master[0]
  any_errors_fatal: true
  roles:
    - { role: kargo-defaults}
    - { role: paas-apps, tags: ["paas-apps", "apps"] }

- hosts: ingress
  gather_facts: false
  roles:
    - { role: kargo-defaults}
    - { role: paas-apps/ingress, tags: ["paas-apps", "ingress"] }

- hosts: zookeeper
  gather_facts: false
  roles:
    - { role: kargo-defaults}
    - { role: elk/zookeeper, tags: ["elk", "zookeeper"] }

- hosts: kafka
  gather_facts: false
  roles:
    - { role: kargo-defaults }
    - { role: elk/kafka, tags: ["elk", "kafka"] }

- hosts: logstash
  gather_facts: false
  roles:
    - { role: kargo-defaults }
    - { role: elk/logstash, tags: ["elk", "logstash"] }

- hosts: es
  gather_facts: false
  roles:
    - { role: kargo-defaults }
    - { role: elk/es, tags: ["elk", "es"] }

- hosts: k8s-cluster
  any_errors_fatal: true
  gather_facts: false
  roles:
      - { role: kargo-defaults }
      - { role: fluent, tags: ["paas-apps","fluent"] }
