---
- name:  nginx-proxy | copy nginx imgaes
  copy:
      src: "{{ playbook_dir }}/tar/paas-apps/nginx.tar"
      dest: /root/
      
- name:  nginx-proxy | load nginx imgaes
  shell: "{{docker_bin_dir}}/docker load -i /root/nginx.tar"

- name: nginx-proxy | Write static pod
  template:
    src: manifests/nginx-proxy.manifest.j2
    dest: "{{kube_manifest_dir}}/nginx-proxy.yml"

- name: nginx-proxy | Make nginx directory
  file:
    path: /etc/nginx
    state: directory
    mode: 0700
    owner: root

- name: nginx-proxy | Write nginx-proxy configuration
  template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf"
    owner: root
    mode: 0755
    backup: yes
