---
- hosts: zookeeper
  gather_facts: false
  roles:
    - { role: kargo-defaults}
    - { role: elk/zookeeper, tags: ["elk", "zookeeper"] }

- hosts: kafka
  gather_facts: false
  roles:
    - { role: kargo-defaults }
    - { role: elk/kafka, tags: ["elk", "kafka"] }

- hosts: logstash
  gather_facts: false
  roles:
    - { role: kargo-defaults }
    - { role: elk/logstash, tags: ["elk", "logstash"] }

- hosts: es
  gather_facts: false
  roles:
    - { role: kargo-defaults }
    - { role: elk/es, tags: ["elk", "es"] }
