docker_kernel_min_version: '0'

docker_versioned_pkg:
  'latest': docker
  '1.11': docker-1:1.11.2
  '1.12': docker-1:1.12.5

docker_package_info:
  pkg_mgr: dnf
  pkgs:
    - name: "{{ docker_versioned_pkg[docker_version | string] }}"

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
