---
dependencies:
  - role: network_plugin/calico
    when: kube_network_plugin == 'calico'
    tags:
      - calico

  - role: network_plugin/flannel
    when: kube_network_plugin == 'flannel'
    tags:
      - flannel
