apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: fluentd-base
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: fluentd-base
    spec:
      containers:
      - image: registry.paas/library/fluentd-base:v0.5
        imagePullPolicy: IfNotPresent
        name: fluentd-base
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/openresty/nginx/logs/
          name: nginx-log
        - mountPath: /etc/fluent/
          name: fluent
        - name: app-log
          mountPath: /dcos/docker/containers
        - name: local-time
          mountPath: /etc/localtime
        - name: k8s-log
          mountPath: /var/log/containers
        - name: k8s-pods
          mountPath: /var/log/pods
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
      - hostPath:
          path: /usr/local/openresty/nginx/logs/
        name: nginx-log
      - name: app-log
        hostPath:
          path: /dcos/docker/containers
      - name: k8s-log
        hostPath:
          path: /var/log/containers
      - name: local-time
        hostPath:
          path: /etc/localtime
      - name: k8s-pods
        hostPath:
          path: /var/log/pods
      - configMap:
          defaultMode: 420
          items:
          - key: fluent.conf
            path: fluent.conf
          name: baselog-config
        name: fluent
      hostNetwork: true
