---
- name: Kubernetes Data Collection | Write kubernetes influxdb yaml
  template:
      src:  influxdb.yml.j2
      dest: "{{kube_config_dir}}/influxdb.yml"
      mode: 0644

- name: Kubernetes Data Collection | Check if monitoring-influxdb svc exists
  command: "{{ bin_dir }}/kubectl get svc monitoring-influxdb -n {{system_namespace}}"
  register: 'monitoringinfluxdbsvc'
  changed_when: False
  failed_when: False
  
- name: Kubernetes Data Collection | Check if monitoring-influxdb deploy exists
  command: "{{ bin_dir }}/kubectl get deploy monitoring-influxdb -n {{system_namespace}}"
  register: 'monitoringinfluxdbdeploy'
  changed_when: False
  failed_when: False

- name: Kubernetes Data Collection | Start kubernetes influxdb app
  kube:
      name: "monitoring-influxdb"
      kubectl: "{{bin_dir}}/kubectl"
      filename: "{{kube_config_dir}}/influxdb.yml"
      namespace: "{{system_namespace}}"
  when: monitoringinfluxdbsvc|failed and monitoringinfluxdbdeploy|failed
#  ignore_errors: yes
